### ISSUE TITLE
implement reminder emails

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/tamarin#10]
- [ ] 15j before the end of the membership 
- [ ]  the the day when the membership expired,
- [ ] 15 days after expirations

Mail Design
- use action template
  https://github.com/mailgun/transactional-email-templates/tree/master/templates
- object : membership will expire 
- message Ex

> Hi Bolo,
> 
> Just a friendly reminder that your Basecamp 60-day free trial ends in a few days.
- add button **abonnement**

**Comment by gscardine** [comment]
Hi Bolo,

I have already created the script to send the emails, but I'm still working on setting up the scheduler in Heroku.

(Nevermind the errors I wrote here about before, I solved them haha)

**Comment by gscardine** [comment]
It worked!

I manually deployed my branch `reminder-emails` in Heroku to be able to test.

You just need to add/edit a user's membership and set it to either: (1) today; (2) 15 days ago; (3) 15 days from today. 
I set the scheduler to run daily at 7:30 UTC, but you can change the time so that you can see the tests faster: https://scheduler.heroku.com/dashboard
![screenshot_reminder_emails](https://cloud.githubusercontent.com/assets/2302126/15090858/fc0e272a-140c-11e6-9f5b-62ddecdaa643.jpg)

Afterwards I will record a video for Marie.

**Comment by bolom** [comment]
@gscardine where is the script?. I think the easier solution is to create the script in ruby.

**Comment by bolom** [comment]
@rmonteiro89 could you help @gscardine to create the scrip in ruby. It will be easier i thing to use php

**Comment by bolom** [comment]
working
